# this notebook shows backtestlib.optimizer.BenchMark etc.

In [70]:
import sys
sys.path.insert(0, "..")
from  backtestlib.optimizer import BenchMark, SampleBased
import pandas as pd
import numpy as np
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [71]:
signal = pd.Series(data = [1,2,2,-2,-3],index = ['AAPL','GOOGLE','MMM','BAC','GS'])
signal

AAPL      1
GOOGLE    2
MMM       2
BAC      -2
GS       -3
dtype: int64

In [72]:
opt = BenchMark()
opt.optimize(signal = signal)

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [73]:
c = 0.02
sample_var = np.diag(np.ones(len(signal)))*(1-c) + c*np.ones((len(signal),len(signal)))
sample_var

array([[1.  , 0.02, 0.02, 0.02, 0.02],
       [0.02, 1.  , 0.02, 0.02, 0.02],
       [0.02, 0.02, 1.  , 0.02, 0.02],
       [0.02, 0.02, 0.02, 1.  , 0.02],
       [0.02, 0.02, 0.02, 0.02, 1.  ]])

In [74]:
opt = SampleBased()
opt.optimize(signal = signal,sample_var = sample_var)

array([ 1.02040816,  2.04081633,  2.04081633, -2.04081633, -3.06122449])